feat: handle additional commit path, not commit -A.

diff --git a/.github/workflows/_test-update-packagejson.yaml b/.github/workflows/_test-update-packagejson.yaml
--- a/.github/workflows/_test-update-packagejson.yaml
+++ b/.github/workflows/_test-update-packagejson.yaml
@@ -40,6 +40,7 @@ jobs:
         ./sandbox/Sandbox.Godot/addons/Foo/plugin.cfg
         ./sandbox/Directory.Build.props
       dotnet-run-path: ./sandbox/VersionOutput/VersionOutput.csproj
+      additional-commit-path: ./sandbox/VersionOutput/version.txt
       tag: ${{ needs.set-tag.outputs.tag }}
       use-bot-token: true
       dry-run: true
@@ -90,6 +91,13 @@ jobs:
     runs-on: ubuntu-24.04
     timeout-minutes: 5
     steps:
+      - uses: Cysharp/Actions/.github/actions/checkout@main
+        with:
+          ref: ${{ needs.update-packagejson.outputs.sha }}
+      - name: Check explicitly allowed dotnet-run output
+        run: |
+          echo -n "FACT: additional-commit-path should contain the generated version. "
+          if [[ "$(cat ./sandbox/VersionOutput/version.txt)" == "${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
       - name: Check update-packagejson with new version should update commit id
         run: |
           echo "DEBUG: tag                : ${{ needs.set-tag.outputs.tag }}"
