chore: try ssh before setup

diff --git a/.github/workflows/benchmark-execute.yaml b/.github/workflows/benchmark-execute.yaml
--- a/.github/workflows/benchmark-execute.yaml
+++ b/.github/workflows/benchmark-execute.yaml
@@ -145,6 +145,23 @@ jobs:
           state: "running"
           title: "Benchmark environment created"
           update: "true"
+      - name: Confirm VM is up and connectable
+        run: |
+          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
+            echo "::group::Connect on $ip"
+              success=false
+              for i in {1..5}; do
+                ssh -o ConnectTimeout=10 azure-user@"$ip" "echo OK" && { success=true; break; }
+                echo "Retrying SSH connection ($i)..."
+                sleep 15
+              done
+              if [ "$success" = false ]; then
+                echo "Failed to connect to $ip after 5 attempts."
+                exit 1
+              fi
+            echo "::endgroup::"
+          done
+        working-directory: ./Actions/.github
       - name: Setup .NET on Benchmark VM
         run: |
           for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
