ci: apply seiton as linter

diff --git a/.github/workflows/benchmark-loader.yaml b/.github/workflows/benchmark-loader.yaml
--- a/.github/workflows/benchmark-loader.yaml
+++ b/.github/workflows/benchmark-loader.yaml
@@ -1,107 +1,110 @@
 name: (R) Benchmark Loader
 
 on:
-  workflow_call:
-    inputs:
-      # required
-      benchmark-name-prefix:
-        description: "Name of the benchamrk environment."
-        required: true
-        type: string
-      benchmark-config-path:
-        description: "Benchmark loader yaml file path"
-        required: true
-        type: string
-    outputs:
-      is-benchmarkable:
-        description: "Indicates whether the actor is authorized to run benchmark."
-        value: ${{ jobs.verify.outputs.is-benchmarkable }}
-      matrix:
-        description: "Generated branch and config path matrix"
-        value: ${{ jobs.loader2matrix.outputs.matrix }}
+    workflow_call:
+        inputs:
+            # required
+            benchmark-name-prefix:
+                description: "Name of the benchamrk environment."
+                required: true
+                type: string
+            benchmark-config-path:
+                description: "Benchmark loader yaml file path"
+                required: true
+                type: string
+        outputs:
+            is-benchmarkable:
+                description: "Indicates whether the actor is authorized to run benchmark."
+                value: ${{ jobs.verify.outputs.is-benchmarkable }}
+            matrix:
+                description: "Generated branch and config path matrix"
+                value: ${{ jobs.loader2matrix.outputs.matrix }}
 
 jobs:
-  # is benchmarkable
-  verify:
-    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/benchmark')) || github.event_name == 'push' || github.event_name == 'pull_request' }}
-    outputs:
-      is-benchmarkable: ${{ steps.is-benchmarkable.outputs.authorized }} # true or false
-    permissions:
-      contents: read
-      issues: write
-    runs-on: ubuntu-24.04
-    timeout-minutes: 1
-    steps:
-      - name: Check actor is benchmarkable
-        id: is-benchmarkable
-        uses: Cysharp/Actions/.github/actions/benchmark-runnable@main
-        with:
-          username: ${{ github.actor }}
-      - name: Add request receive reaction
-        if: ${{ github.event.issue.number }}
-        run: |
-          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" -f "content=+1"
-        env:
-          GH_REPO: ${{ github.repository }}
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Comment (Running - Auth Result)
-        uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
-        with:
-          comment: ${{ steps.is-benchmarkable.outputs.authorized == 'true' && 'Benchmark request accepted, creating benchmark environment. :clock1:' || 'Benchmark request rejected, you are not authorized to run benchmark. :warning:'}}
-          state: ${{ steps.is-benchmarkable.outputs.authorized == 'true' && 'running' || 'failed' }}
-          title: ${{ steps.is-benchmarkable.outputs.authorized == 'true' && 'Successfully begin benchmark' || 'Failed to begin benchmark' }}
-          update: "false"
+    # is benchmarkable
+    verify:
+        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/benchmark')) || github.event_name == 'push' || github.event_name == 'pull_request' }}
+        outputs:
+            is-benchmarkable: ${{ steps.is-benchmarkable.outputs.authorized }} # true or false
+        permissions:
+            contents: read
+            issues: write
+        runs-on: ubuntu-24.04
+        timeout-minutes: 1
+        steps:
+            - name: Check actor is benchmarkable
+              id: is-benchmarkable
+              uses: Cysharp/Actions/.github/actions/benchmark-runnable@main
+              with:
+                  username: ${{ github.actor }}
+            - name: Add request receive reaction
+              if: ${{ github.event.issue.number }}
+              run: |
+                  gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" -f "content=+1"
+              env:
+                  GH_REPO: ${{ github.repository }}
+                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            - name: Comment (Running - Auth Result)
+              uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
+              with:
+                  comment: ${{ steps.is-benchmarkable.outputs.authorized == 'true' && 'Benchmark request accepted, creating benchmark environment. :clock1:' || 'Benchmark request rejected, you are not authorized to run benchmark. :warning:'}}
+                  state: ${{ steps.is-benchmarkable.outputs.authorized == 'true' && 'running' || 'failed' }}
+                  title: ${{ steps.is-benchmarkable.outputs.authorized == 'true' && 'Successfully begin benchmark' || 'Failed to begin benchmark' }}
+                  update: "false"
 
-  loader2matrix:
-    if: ${{ needs.verify.outputs.is-benchmarkable == 'true' }}
-    needs: [verify]
-    outputs:
-      matrix: ${{ steps.loader2matrix.outputs.matrix }}
-    permissions:
-      contents: read
-    runs-on: ubuntu-24.04
-    timeout-minutes: 1
-    steps:
-      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
-        with:
-          dotnet-version: 9.0.x
-      - name: Get branch name to checkout
-        id: branch
-        run: |
-          if [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.issue.pull_request.html_url }}" != "" ]]; then
-            # issue_comment (pull_request)
-            branch=$(gh pr view "${{ github.event.issue.pull_request.html_url }}"  --json headRefName | jq -r ".headRefName")
-            echo "name=${branch}" | tee -a "$GITHUB_OUTPUT"
-          else
-            # issue_comment (issue) and other trigger
-            echo "name=${{ github.ref_name }}" | tee -a "$GITHUB_OUTPUT"
-          fi
-      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          ref: ${{ steps.branch.outputs.name }}
-          path: Repo
-          persist-credentials: false
-      - name: Set Cysharp/Actions binary path
-        id: actions-caller
-        run: |
-          branch=main
-          if [[ ${{ github.repository }} == "Cysharp/Actions" ]]; then
-            echo path="dotnet run --project ./src/CysharpActions/CysharpActions.csproj --no-launch-profile --" | tee -a "$GITHUB_OUTPUT"
-            exit
-          elif [[ -f "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" ]]; then
-            echo path="${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" | tee -a "$GITHUB_OUTPUT"
-            chmod +x "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions"
-          else
-            echo "ERROR: CysharpActions binary not found."
-            echo "::group::Debug _actions folder."
-              ls -lR "${{ github.workspace }}/../../_actions/"
-            echo "::endgroup::"
-            echo "::group::Debug _actions/Cysharp/Actions folder."
-              ls -lR "${{ github.workspace }}/../../_actions/Cysharp/Actions/"
-            echo "::endgroup::"
-            exit 1
-          fi
-      - name: Generate Matrix json from config
-        id: loader2matrix
-        run: ${{ steps.actions-caller.outputs.path }} benchmark-loader2matrix --benchmark-name-prefix "${{ inputs.benchmark-name-prefix }}" --config-path "${{ inputs.benchmark-config-path }}" --branch "${{ steps.branch.outputs.name }}"
-        working-directory: Repo
+    loader2matrix:
+        if: ${{ needs.verify.outputs.is-benchmarkable == 'true' }}
+        needs: [verify]
+        outputs:
+            matrix: ${{ steps.loader2matrix.outputs.matrix }}
+        permissions:
+            contents: read
+        runs-on: ubuntu-24.04
+        timeout-minutes: 1
+        steps:
+            - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
+              with:
+                  dotnet-version: 9.0.x
+            - name: Get branch name to checkout
+              id: branch
+              run: |
+                  if [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.issue.pull_request.html_url }}" != "" ]]; then
+                    # issue_comment (pull_request)
+                    branch=$(gh pr view "${{ github.event.issue.pull_request.html_url }}"  --json headRefName | jq -r ".headRefName")
+                    echo "name=${branch}" | tee -a "$GITHUB_OUTPUT"
+                  else
+                    # issue_comment (issue) and other trigger
+                    echo "name=${{ github.ref_name }}" | tee -a "$GITHUB_OUTPUT"
+                  fi
+            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+              with:
+                  ref: ${{ steps.branch.outputs.name }}
+                  path: Repo
+                  persist-credentials: false
+            - name: Set Cysharp/Actions binary path
+              id: actions-caller
+              run: |
+                  branch=main
+                  if [[ ${{ github.repository }} == "Cysharp/Actions" ]]; then
+                    echo path="dotnet run --project ./src/CysharpActions/CysharpActions.csproj --no-launch-profile --" | tee -a "$GITHUB_OUTPUT"
+                    exit
+                  elif [[ -f "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" ]]; then
+                    echo path="${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" | tee -a "$GITHUB_OUTPUT"
+                    chmod +x "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions"
+                  else
+                    echo "ERROR: CysharpActions binary not found."
+                    echo "::group::Debug _actions folder."
+                      ls -lR "${{ github.workspace }}/../../_actions/"
+                    echo "::endgroup::"
+                    echo "::group::Debug _actions/Cysharp/Actions folder."
+                      ls -lR "${{ github.workspace }}/../../_actions/Cysharp/Actions/"
+                    echo "::endgroup::"
+                    exit 1
+                  fi
+            - name: Generate Matrix json from config
+              id: loader2matrix
+              run: ${{ steps.actions-caller.outputs.path }} benchmark-loader2matrix --benchmark-name-prefix "${BENCHMARK_NAME_PREFIX}" --config-path "${BENCHMARK_CONFIG_PATH}" --branch "${{ steps.branch.outputs.name }}"
+              env:
+                  BENCHMARK_NAME_PREFIX: ${{ inputs.benchmark-name-prefix }}
+                  BENCHMARK_CONFIG_PATH: ${{ inputs.benchmark-config-path }}
+              working-directory: Repo
