tmp: no benchmark, just wait

diff --git a/.github/workflows/benchmark-execute.yaml b/.github/workflows/benchmark-execute.yaml
--- a/.github/workflows/benchmark-execute.yaml
+++ b/.github/workflows/benchmark-execute.yaml
@@ -164,83 +164,83 @@ jobs:
           title: "Benchmark environment created"
           update: "true"
       - name: Show GitHub Actions runner public IP
-        run: curl -s curl https://checkip.amazonaws.com
-      - name: Confirm VM is up and connectable
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
-            echo "::group::Connect on $ip"
-              success=false
-              for i in {1..5}; do
-                ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" "echo OK" && { success=true; break; }
-                echo "Retrying SSH connection ($i)..."
-                sleep 15
-              done
-              if [ "$success" = false ]; then
-                echo "Failed to connect to $ip after 5 attempts."
-                exit 1
-              fi
-            echo "::endgroup::"
-          done
-        working-directory: ./Actions/.github
-      - name: Setup .NET on Benchmark VM
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
-            echo "::group::Install on $ip"
-              ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- --dotnet-version ${{ matrix.dotnet-version }}' < ./scripts/dotnet_install.sh
-            echo "::endgroup::"
-          done
-        working-directory: ./Actions/.github
-      - name: Setup apt tools on Benchmark VM
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
-            echo "::group::Install on $ip"
-              ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- --tools "${{ matrix.apt-tools }}"' < ./scripts/apt_install.sh
-            echo "::endgroup::"
-          done
-        working-directory: ./Actions/.github
-      - name: Clone repository on VM
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
-            echo "::group::Install on $ip"
-              ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- --branch "${{ inputs.branch }}" --owner "${{ github.repository_owner }}" --repo "${{ github.event.repository.name }}"' < ./scripts/git_clone.sh
-            echo "::endgroup::"
-          done
-        working-directory: ./Actions/.github
-      - name: Comment (Progress - Server begin)
-        uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
-        with:
-          comment: "Repository successfully prepared, starting server. :clock6:"
-          state: "running"
-          title: "Benchmark begin"
-          update: "true"
-      - name: Run benchmark server on VM
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running' && name=='${{ env.BENCHMARK_SERVER_NAME }}'].publicIps" -o tsv); do
-            ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- ${{ matrix.benchmark-server-run-script-args }}' < ${{ matrix.benchmark-server-run-script-path }}
-          done
-        working-directory: ./Repo/
-      - name: Comment (Progress - Benchmark begin)
-        uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
-        with:
-          comment: "Server successfully started, starting benchmark. :clock9:"
-          state: "running"
-          title: "Benchmark begin"
-          update: "true"
-      - name: Run benchmark client on VM
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running' && name=='${{ env.BENCHMARK_CLIENT_NAME }}'].publicIps" -o tsv); do
-            ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- ${{ matrix.benchmark-client-run-script-args }}' < ${{ matrix.benchmark-client-run-script-path }}
-          done
-        working-directory: ./Repo/
-        timeout-minutes: ${{ fromJson(matrix.benchmark-timeout-min || 10) }}
-        continue-on-error: true # continue next benchmark even benchmark failed for this job
-      - name: Stop benchmark server on VM
-        if: ${{ matrix.benchmark-server-stop-script-path != '' }}
-        run: |
-          for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running' && name=='${{ env.BENCHMARK_SERVER_NAME }}'].publicIps" -o tsv); do
-            ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- ${{ matrix.benchmark-server-run-script-args }}' < ${{ matrix.benchmark-server-stop-script-path }}
-          done
-        working-directory: ./Repo/
+        run: curl -s https://checkip.amazonaws.com
+      # - name: Confirm VM is up and connectable
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
+      #       echo "::group::Connect on $ip"
+      #         success=false
+      #         for i in {1..5}; do
+      #           ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" "echo OK" && { success=true; break; }
+      #           echo "Retrying SSH connection ($i)..."
+      #           sleep 15
+      #         done
+      #         if [ "$success" = false ]; then
+      #           echo "Failed to connect to $ip after 5 attempts."
+      #           exit 1
+      #         fi
+      #       echo "::endgroup::"
+      #     done
+      #   working-directory: ./Actions/.github
+      # - name: Setup .NET on Benchmark VM
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
+      #       echo "::group::Install on $ip"
+      #         ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- --dotnet-version ${{ matrix.dotnet-version }}' < ./scripts/dotnet_install.sh
+      #       echo "::endgroup::"
+      #     done
+      #   working-directory: ./Actions/.github
+      # - name: Setup apt tools on Benchmark VM
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
+      #       echo "::group::Install on $ip"
+      #         ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- --tools "${{ matrix.apt-tools }}"' < ./scripts/apt_install.sh
+      #       echo "::endgroup::"
+      #     done
+      #   working-directory: ./Actions/.github
+      # - name: Clone repository on VM
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running'].publicIps" -o tsv); do
+      #       echo "::group::Install on $ip"
+      #         ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- --branch "${{ inputs.branch }}" --owner "${{ github.repository_owner }}" --repo "${{ github.event.repository.name }}"' < ./scripts/git_clone.sh
+      #       echo "::endgroup::"
+      #     done
+      #   working-directory: ./Actions/.github
+      # - name: Comment (Progress - Server begin)
+      #   uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
+      #   with:
+      #     comment: "Repository successfully prepared, starting server. :clock6:"
+      #     state: "running"
+      #     title: "Benchmark begin"
+      #     update: "true"
+      # - name: Run benchmark server on VM
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running' && name=='${{ env.BENCHMARK_SERVER_NAME }}'].publicIps" -o tsv); do
+      #       ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- ${{ matrix.benchmark-server-run-script-args }}' < ${{ matrix.benchmark-server-run-script-path }}
+      #     done
+      #   working-directory: ./Repo/
+      # - name: Comment (Progress - Benchmark begin)
+      #   uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
+      #   with:
+      #     comment: "Server successfully started, starting benchmark. :clock9:"
+      #     state: "running"
+      #     title: "Benchmark begin"
+      #     update: "true"
+      # - name: Run benchmark client on VM
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running' && name=='${{ env.BENCHMARK_CLIENT_NAME }}'].publicIps" -o tsv); do
+      #       ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- ${{ matrix.benchmark-client-run-script-args }}' < ${{ matrix.benchmark-client-run-script-path }}
+      #     done
+      #   working-directory: ./Repo/
+      #   timeout-minutes: ${{ fromJson(matrix.benchmark-timeout-min || 10) }}
+      #   continue-on-error: true # continue next benchmark even benchmark failed for this job
+      # - name: Stop benchmark server on VM
+      #   if: ${{ matrix.benchmark-server-stop-script-path != '' }}
+      #   run: |
+      #     for ip in $(az vm list -d --resource-group "${{ env.BENCHMARK_RESOURCE_GROUP }}" --query "[?powerState=='VM running' && name=='${{ env.BENCHMARK_SERVER_NAME }}'].publicIps" -o tsv); do
+      #       ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_ed25519 azure-user@"$ip" 'bash -s -- ${{ matrix.benchmark-server-run-script-args }}' < ${{ matrix.benchmark-server-stop-script-path }}
+      #     done
+      #   working-directory: ./Repo/
       - name: Comment (Result - Benchmark complete)
         uses: Cysharp/Actions/.github/actions/benchmark-progress-comment@main
         with:
@@ -273,3 +273,18 @@ jobs:
           title: "Benchmark cancelled"
           update: "true"
         if: ${{ cancelled() }}
+
+  debug-sleep:
+    needs: [benchmark]
+    environment:
+      name: benchmark
+    permissions:
+      contents: read
+      issues: write
+      pull-requests: write
+      id-token: write
+    runs-on: ubuntu-24.04
+    timeout-minutes: 30
+    steps:
+      - name: sleep a while
+        run: sleep 1800
