feat: specify wild card for release asset

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -137,6 +137,20 @@ jobs:
         run: |
           while read -r asset_path; do
             if [[ "${asset_path}" == "" ]]; then continue; fi
+            # is it a wildcard?
+            # shellcheck disable=SC2086
+            if [[ "$input_str" == *\** || "$input_str" == *\?* ]]; then
+              # shellcheck disable=SC2086
+              if ! ls -l ${asset_path}; then
+                echo "Specified nuget package not found. path: $asset_path"
+                if [[ "${asset_path}" == *.nupkg ]]; then
+                  echo ".nupkg must be included in the artifact."
+                  exit 1
+                fi
+              fi
+              continue
+            fi
+            # is it a file?
             if [[ ! -f "${asset_path}" ]]; then
               echo "Specified asset not found. path: ${asset_path}"
               exit 1
@@ -179,6 +193,15 @@ jobs:
         run: |
           while read -r asset_path; do
             if [[ "${asset_path}" == "" ]]; then continue; fi
+            # is it a wildcard?
+            # shellcheck disable=SC2086
+            if [[ "$input_str" == *\** || "$input_str" == *\?* ]]; then
+              for file in ${asset_path}; do
+                gh release upload ${{ inputs.tag }} "${file}"
+              done
+              continue
+            fi
+            # is it a file?
             gh release upload ${{ inputs.tag }} "${asset_path}"
           done <<< "${{ inputs.release-asset-path }}"
         if: ${{ inputs.release-upload }}
