style: format

diff --git a/.github/workflows/increment-version.yaml b/.github/workflows/increment-version.yaml
--- a/.github/workflows/increment-version.yaml
+++ b/.github/workflows/increment-version.yaml
@@ -1,79 +1,79 @@
 name: (R) Increment version
 
 on:
-    workflow_call:
-        inputs:
-            ref:
-                description: "checkout ref"
-                required: false
-                type: string
-                default: ""
-            tag:
-                description: "git tag you want create. (sample 1.0.0)"
-                required: true
-                type: string
-            type:
-                description: "type: version increment type. (major, minor, patch)"
-                required: true
-                type: string
-            prefix:
-                description: "version prefix. (sample v for v1.0.0)"
-                required: false
-                type: string
-                default: ""
-            suffix:
-                description: "version suffix. (sample -beta for 1.0.0-beta)"
-                required: false
-                type: string
-                default: ""
-        outputs:
-            version:
-                description: Git branch name created.
-                value: ${{ jobs.new-version.outputs.version }}
+  workflow_call:
+    inputs:
+      ref:
+        description: "checkout ref"
+        required: false
+        type: string
+        default: ""
+      tag:
+        description: "git tag you want create. (sample 1.0.0)"
+        required: true
+        type: string
+      type:
+        description: "type: version increment type. (major, minor, patch)"
+        required: true
+        type: string
+      prefix:
+        description: "version prefix. (sample v for v1.0.0)"
+        required: false
+        type: string
+        default: ""
+      suffix:
+        description: "version suffix. (sample -beta for 1.0.0-beta)"
+        required: false
+        type: string
+        default: ""
+    outputs:
+      version:
+        description: Git branch name created.
+        value: ${{ jobs.new-version.outputs.version }}
 
 jobs:
-    new-version:
-        permissions:
-            actions: read
-            contents: read
-        runs-on: ubuntu-24.04
-        timeout-minutes: 5
-        outputs:
-            version: ${{ steps.new-version.outputs.version }}
-        steps:
-            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-              with:
-                  ref: ${{ inputs.ref }}
-                  persist-credentials: false
-            - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
-              with:
-                  dotnet-version: 9.0.x
-            - name: Set Cysharp/Actions binary path
-              id: actions-caller
-              run: |
-                  branch=main
-                  if [[ ${{ github.repository }} == "Cysharp/Actions" ]]; then
-                    echo path="dotnet run --project ./src/CysharpActions/CysharpActions.csproj --no-launch-profile --" | tee -a "$GITHUB_OUTPUT"
-                    exit
-                  elif [[ -f "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" ]]; then
-                    echo path="${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" | tee -a "$GITHUB_OUTPUT"
-                    chmod +x "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions"
-                  else
-                    echo "ERROR: CysharpActions binary not found."
-                    echo "::group::Debug _actions folder."
-                      ls -lR "${{ github.workspace }}/../../_actions/"
-                    echo "::endgroup::"
-                    echo "::group::Debug _actions/Cysharp/Actions folder."
-                      ls -lR "${{ github.workspace }}/../../_actions/Cysharp/Actions/"
-                    echo "::endgroup::"
-                    exit 1
-                  fi
+  new-version:
+    permissions:
+      actions: read
+      contents: read
+    runs-on: ubuntu-24.04
+    timeout-minutes: 5
+    outputs:
+      version: ${{ steps.new-version.outputs.version }}
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          ref: ${{ inputs.ref }}
+          persist-credentials: false
+      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
+        with:
+          dotnet-version: 9.0.x
+      - name: Set Cysharp/Actions binary path
+        id: actions-caller
+        run: |
+          branch=main
+          if [[ ${{ github.repository }} == "Cysharp/Actions" ]]; then
+            echo path="dotnet run --project ./src/CysharpActions/CysharpActions.csproj --no-launch-profile --" | tee -a "$GITHUB_OUTPUT"
+            exit
+          elif [[ -f "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" ]]; then
+            echo path="${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions" | tee -a "$GITHUB_OUTPUT"
+            chmod +x "${{ github.workspace }}/../../_actions/Cysharp/Actions/${branch}/actions/Linux-${{ runner.arch }}/CysharpActions"
+          else
+            echo "ERROR: CysharpActions binary not found."
+            echo "::group::Debug _actions folder."
+              ls -lR "${{ github.workspace }}/../../_actions/"
+            echo "::endgroup::"
+            echo "::group::Debug _actions/Cysharp/Actions folder."
+              ls -lR "${{ github.workspace }}/../../_actions/Cysharp/Actions/"
+            echo "::endgroup::"
+            exit 1
+          fi
 
-            - name: Increment version
-              id: new-version
-              run: ${{ steps.actions-caller.outputs.path }} increment-version --version "${TAG}" --type "${TYPE}" --prefix "${PREFIX}" --suffix "${SUFFIX}"
-              env:
-                  TAG: ${{ inputs.tag }}
-                  TYPE: ${{ inputs.type }}
-                  PREFIX: ${{ inputs.prefix }}
-                  SUFFIX: ${{ inputs.suffix }}
+      - name: Increment version
+        id: new-version
+        run: ${{ steps.actions-caller.outputs.path }} increment-version --version "${TAG}" --type "${TYPE}" --prefix "${PREFIX}" --suffix "${SUFFIX}"
+        env:
+          TAG: ${{ inputs.tag }}
+          TYPE: ${{ inputs.type }}
+          PREFIX: ${{ inputs.prefix }}
+          SUFFIX: ${{ inputs.suffix }}
