ci: fix test

diff --git a/.github/workflows/test-benchmark_config2matrix.yaml b/.github/workflows/test-benchmark_config2matrix.yaml
--- a/.github/workflows/test-benchmark_config2matrix.yaml
+++ b/.github/workflows/test-benchmark_config2matrix.yaml
@@ -11,12 +11,12 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Run benchmark_config2matrix
-        id: result
+        id: actual
         run: bash ./.github/scripts/benchmark_config2matrix.sh --benchmark-config-path ./.github/scripts/tests/template_benchmark_config.yaml
       - name: Test
         run: |
-          echo "DEBUG: output: ${{ steps.result.outputs.matrix }}"
+          expected=$(jq -c < ./.github/scripts/tests/template_benchmark_config.json)
+          actual=$(echo '${{ steps.actual.outputs.matrix }}' | jq -c)
 
           echo -n "FACT: matrix is sane as expected json"
-          expected=$(jq -c < ./.github/scripts/tests/template_benchmark_config.json)
-          if [[ "${{ steps.result.outputs.matrix }}" == "$expected" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "$actual" == "$expected" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
