ci: fix test

diff --git a/.github/workflows/test-increment-version.yaml b/.github/workflows/test-increment-version.yaml
--- a/.github/workflows/test-increment-version.yaml
+++ b/.github/workflows/test-increment-version.yaml
@@ -111,7 +111,7 @@ jobs:
     runs-on: ubuntu-24.04
     timeout-minutes: 5
     steps:
-      - name: Check update-packagejson with new version should update commit id
+      - name: Check increment-version with new version
         run: |
           echo "DEBUG: tag                    : ${{ needs.set-tag.outputs.tag }}"
           echo "DEBUG: new-version-major      : ${{ needs.new-version-major.outputs.version }}"
@@ -126,7 +126,7 @@ jobs:
           echo -n "FACT: version for new-version-minor should be expected. "
           if [[ "${{ needs.new-version-minor.outputs.version }}" == "1.1.0" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: version for new-version-patch should be expected. "
-          if [[ "${{ needs.new-version-patch.outputs.version }}" == "1.0.1-dev" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.new-version-patch.outputs.version }}" == "1.0.1" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: version for new-version-prefix should be expected. "
           if [[ "${{ needs.new-version-prefix.outputs.version }}" == "Ver.1.0.1" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: version for new-version-suffix should be expected. "
