feat: change to workflow

diff --git a/.github/workflows/test-validate-tag.yaml b/.github/workflows/test-validate-tag.yaml
--- a/.github/workflows/test-validate-tag.yaml
+++ b/.github/workflows/test-validate-tag.yaml
@@ -13,28 +13,34 @@ on:
     branches: ["main"]
 
 jobs:
+  validate:
+    if: ${{ github.actor != 'dependabot[bot]' }}
+    uses: ./.github/workflows/validate-tag.yaml
+    with:
+      tag: "1.10.0"
+      no-fail-on-error: false
+    secrets: inherit
+
+  validate2:
+    if: ${{ github.actor != 'dependabot[bot]' }}
+    uses: ./.github/workflows/validate-tag.yaml
+    with:
+      tag: "1.0.0"
+      no-fail-on-error: true
+    secrets: inherit
+
   test:
+    needs: [validate, validate2]
     runs-on: ubuntu-latest
     timeout-minutes: 3
     steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/validate-tag
-        id: validate
-        with:
-          tag: ${{ inputs.tag || '1.10.0' }}
-          no-fail-on-error: false
-      - uses: ./.github/actions/validate-tag
-        id: validate2
-        with:
-          tag: ${{ inputs.tag || '1.0.0' }}
-          no-fail-on-error: true
       - name: Test
         run: |
-          echo "DEBUG: validate: ${{ steps.validate.outputs.result }}"
-          echo "DEBUG: validate2: ${{ steps.validate2.outputs.result }}"
+          echo "DEBUG: validate: ${{ needs.validate.outputs.result }}"
+          echo "DEBUG: validate2: ${{ needs.validate2.outputs.result }}"
 
           echo -n "FACT: tag is newer then current release"
-          if [[ "${{ steps.validate.outputs.result }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.validate.outputs.result }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: tag is old then current release"
-          if [[ "${{ steps.validate2.outputs.result }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.validate2.outputs.result }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
