chore: reuse branch name for test

diff --git a/.github/workflows/test-clean-packagejson-branch.yaml b/.github/workflows/test-clean-packagejson-branch.yaml
--- a/.github/workflows/test-clean-packagejson-branch.yaml
+++ b/.github/workflows/test-clean-packagejson-branch.yaml
@@ -10,28 +10,33 @@ on:
 jobs:
   create-branch:
     runs-on: ubuntu-latest
+    outputs:
+      branch-name: ${{ steps.branch.outputs.name }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Set branch name
+        id: branch
+        run: echo "name=test-branch-${{ github.run_id }}" | tee -a "$GITHUB_OUTPUT"
       - name: Add some file change
         run: echo "test" > test.txt
       - name: Create branch
         run: |
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
-          git switch -c test-branch-${{ github.run_id }}
+          git switch -c ${{ steps.branch.outputs.name }}
           git add .
           git commit -m "test"
-          git push origin test-branch-${{ github.run_id }}
+          git push origin ${{ steps.branch.outputs.name }}
 
   cleanup:
     needs: [create-branch]
     uses: ./.github/workflows/clean-packagejson-branch.yaml
     with:
-      branch: test-branch-${{ github.run_id }}
+      branch: ${{ needs.create-branch.outputs.branch-name }}
 
   test:
-    needs: [cleanup]
+    needs: [create-branch, cleanup]
     runs-on: ubuntu-latest
     steps:
       - name: Test branch deleted
@@ -42,9 +47,9 @@ jobs:
 
           # test
           echo -n "FACT: remote branch should not exists. "
-          if ! gh api /repos/${{ github.repository }}/branches | jq -r '.[].name' | grep "test-branch-${{ github.run_id }}" >/dev/null; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if ! gh api /repos/${{ github.repository }}/branches | jq -r '.[].name' | grep "${{ needs.create-branch.outputs.branch-name }}" >/dev/null; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: remote branch should not retrieve. "
-          if ! gh api /repos/${{ github.repository }}/branches/test-branch-${{ github.run_id }} >/dev/null 2>&1; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if ! gh api /repos/${{ github.repository }}/branches/${{ needs.create-branch.outputs.branch-name }} >/dev/null 2>&1; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
