chore: success true|false

diff --git a/.github/workflows/test-validate-tag.yaml b/.github/workflows/test-validate-tag.yaml
--- a/.github/workflows/test-validate-tag.yaml
+++ b/.github/workflows/test-validate-tag.yaml
@@ -36,11 +36,11 @@ jobs:
     steps:
       - name: Test
         run: |
-          echo "DEBUG: validate: ${{ needs.validate.outputs.result }}"
-          echo "DEBUG: validate2: ${{ needs.validate2.outputs.result }}"
+          echo "DEBUG: validate: ${{ needs.validate.outputs.success }}"
+          echo "DEBUG: validate2: ${{ needs.validate2.outputs.success }}"
 
           echo -n "FACT: tag is newer then current release"
-          if [[ "${{ needs.validate.outputs.result }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.validate.outputs.success }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: tag is old then current release"
-          if [[ "${{ needs.validate2.outputs.result }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.validate2.outputs.success }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
