chore: actionlint warning

diff --git a/.github/workflows/test-clean-packagejson-branch.yaml b/.github/workflows/test-clean-packagejson-branch.yaml
--- a/.github/workflows/test-clean-packagejson-branch.yaml
+++ b/.github/workflows/test-clean-packagejson-branch.yaml
@@ -53,9 +53,9 @@ jobs:
           echo "DEBUG: cleanup2: ${{ needs.cleanup2.outputs.branch-deleted }}"
 
           echo -n "FACT: cleanup deleted branch. "
-          [[ "${{ needs.cleanup.outputs.branch-deleted }}" == "true" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.cleanup.outputs.branch-deleted }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
           echo -n "FACT: cleanup2 skip delete branch. "
-          [[ "${{ needs.cleanup2.outputs.branch-deleted }}" != "true" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.cleanup2.outputs.branch-deleted }}" != "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: remote branch should not exists. "
           if ! gh api /repos/${{ github.repository }}/branches | jq -r '.[].name' | grep "${{ needs.create-branch.outputs.branch-name }}" >/dev/null; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
diff --git a/.github/workflows/test-update-packagejson.yaml b/.github/workflows/test-update-packagejson.yaml
--- a/.github/workflows/test-update-packagejson.yaml
+++ b/.github/workflows/test-update-packagejson.yaml
@@ -70,18 +70,18 @@ jobs:
           echo "DEBUG: update-packagejson2: ${{ needs.update-packagejson2.outputs.sha }}"
 
           echo -n "FACT: sha for update-packagejson should be updated. "
-          [[ "${{ needs.update-packagejson.outputs.sha }}" != "${{ github.sha }}" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.update-packagejson.outputs.sha }}" != "${{ github.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
           echo -n "FACT: sha for update-packagejson2 should be updated. "
-          [[ "${{ needs.update-packagejson2.outputs.sha }}" != "${{ github.sha }}" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.update-packagejson2.outputs.sha }}" != "${{ github.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
           echo -n "FACT: sha for update-packagejson and update-packagejson2 should have same commit id. "
-          [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson2.outputs.sha }}" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson2.outputs.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: is-branch-created for update-packagejson should be created. "
-          [[ "${{ needs.update-packagejson.outputs.is-branch-created }}" == "true" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.update-packagejson.outputs.is-branch-created }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
           echo -n "FACT: is-branch-created for update-packagejson2 should be not created. "
-          [[ "${{ needs.update-packagejson2.outputs.is-branch-created }}" == "false" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.update-packagejson2.outputs.is-branch-created }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
-          echo -n "FACT: branch-name for update-packagejson should be exists. "
-          [[ "${{ needs.update-packagejson.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          echo -n "FACT: branch-name for update-packagejson should be expected. "
+          if [[ "${{ needs.update-packagejson.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
           echo -n "FACT: branch-name for update-packagejson2 should be exists. "
-          [[ "${{ needs.update-packagejson2.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]] && echo "[O PASS]" || (echo "[X FAIL]" && exit 1)
+          if [[ "${{ needs.update-packagejson2.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
