chore: test error message

diff --git a/.github/workflows/test-benchmark_scripts.yaml b/.github/workflows/test-benchmark_scripts.yaml
--- a/.github/workflows/test-benchmark_scripts.yaml
+++ b/.github/workflows/test-benchmark_scripts.yaml
@@ -19,7 +19,7 @@ jobs:
           actual=$(echo '${{ steps.actual.outputs.matrix }}' | jq -c)
 
           echo -n "FACT: matrix is sane as expected json. "
-          if [[ "$actual" == "$expected" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "$actual" == "$expected" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
 
   loader2matrix:
     runs-on: ubuntu-latest
@@ -41,5 +41,5 @@ jobs:
           actual_params=$(echo '${{ steps.actual_params.outputs.matrix }}' | jq -c)
 
           echo -n "FACT: matrix is sane as expected json. "
-          if [[ "$actual_config" == "$expected_config" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          if [[ "$actual_params" == "$expected_params" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "$actual_config" == "$expected_config" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
+          if [[ "$actual_params" == "$expected_params" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
diff --git a/.github/workflows/test-checkout.yaml b/.github/workflows/test-checkout.yaml
--- a/.github/workflows/test-checkout.yaml
+++ b/.github/workflows/test-checkout.yaml
@@ -13,8 +13,17 @@ jobs:
       - uses: Cysharp/Actions/.github/actions/checkout@main
       - name: Test
         run: |
-          if [[ -f "README.md" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          if [[ -d ".github" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          if [[ -f ".github/actions/checkout/action.yaml" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          if [[ -f ".github/workflows/create-release.yaml" ]]: then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          if [[ -d "src" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          echo -n "FACT: README.md exists. "
+          if [[ -f "README.md" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
+
+          echo -n "FACT: .github/ exists. "
+          if [[ -d ".github/" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
+
+          echo -n "FACT: .github/actions/checkout/action.yaml exists. "
+          if [[ -f ".github/actions/checkout/action.yaml" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
+
+          echo -n "FACT: .github/workflows/create-release.yaml exists. "
+          if [[ -f ".github/workflows/create-release.yaml" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
+
+          echo -n "FACT: src/ exists. "
+          if [[ -d "src/" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
diff --git a/.github/workflows/test-update-packagejson.yaml b/.github/workflows/test-update-packagejson.yaml
--- a/.github/workflows/test-update-packagejson.yaml
+++ b/.github/workflows/test-update-packagejson.yaml
@@ -81,20 +81,20 @@ jobs:
           echo "DEBUG: update-packagejson2: ${{ needs.update-packagejson2.outputs.sha }}"
 
           echo -n "FACT: sha for update-packagejson should be updated. "
-          if [[ "${{ needs.update-packagejson.outputs.sha }}" != "${{ github.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson.outputs.sha }}" != "${{ github.sha }}" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: sha for update-packagejson2 should be updated. "
-          if [[ "${{ needs.update-packagejson2.outputs.sha }}" != "${{ github.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson2.outputs.sha }}" != "${{ github.sha }}" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: sha for update-packagejson and update-packagejson2 should have same commit id. "
-          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson2.outputs.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson2.outputs.sha }}" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: sha for update-packagejson and update-packagejson3 should have same commit id. "
-          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson3.outputs.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson3.outputs.sha }}" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
 
           echo -n "FACT: branch-name for update-packagejson should be expected. "
-          if [[ "${{ needs.update-packagejson.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: branch-name for update-packagejson2 should be empty. "
-          if [[ "${{ needs.update-packagejson2.outputs.branch-name }}" == "" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson2.outputs.branch-name }}" == "" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
           echo -n "FACT: branch-name for update-packagejson3 should be empty. "
-          if [[ "${{ needs.update-packagejson3.outputs.branch-name }}" == "" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.update-packagejson3.outputs.branch-name }}" == "" ]]; then echo "[O PASS]"; else echo "::error::[X FAIL]" && exit 1; fi
         env:
           HEAD_REF: ${{ github.head_ref }}
 
