ci: add test

diff --git a/.github/workflows/test-clean-packagejson-branch.yaml b/.github/workflows/test-clean-packagejson-branch.yaml
--- a/.github/workflows/test-clean-packagejson-branch.yaml
+++ b/.github/workflows/test-clean-packagejson-branch.yaml
@@ -15,11 +15,27 @@ jobs:
         uses: actions/checkout@v2
       - name: Create branch
         run: |
-          git checkout -b test-branch
-          git push origin test-branch
+          git checkout -b test-branch-${{ github.run_id }}
+          git push origin test-branch-${{ github.run_id }}
 
   cleanup:
     needs: [create-branch]
     uses: ./.github/workflows/clean-packagejson-branch.yaml
     with:
-      branch: test-branch
+      branch: test-branch-${{ github.run_id }}
+
+  test:
+    needs: [cleanup]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Test branch deleted
+        run: |
+          # list branch
+          gh api /repos/${{ github.repository }}/branches
+
+          # test
+          echo -n "FACT: remote branch should not exists. "
+          if ! gh api /repos/${{ github.repository }}/branches | jq '.[] | select(.name == "test-branch-${{ github.run_id }}")'; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+
+          echo -n "FACT: remote branch should not retrieve. "
+          if ! gh api /repos/${{ github.repository }}/branches/test-branch-${{ github.run_id }}; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
