chore: escape commit message for Linux

diff --git a/.github/workflows/test-update-packagejson.yaml b/.github/workflows/test-update-packagejson.yaml
--- a/.github/workflows/test-update-packagejson.yaml
+++ b/.github/workflows/test-update-packagejson.yaml
@@ -91,26 +91,19 @@ jobs:
           echo -n "FACT: sha for update-packagejson and update-packagejson3 should have same commit id. "
           if [[ "${{ needs.update-packagejson.outputs.sha }}" == "${{ needs.update-packagejson3.outputs.sha }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
-          echo -n "FACT: is-branch-created for update-packagejson should be created. "
-          if [[ "${{ needs.update-packagejson.outputs.is-branch-created }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          echo -n "FACT: is-branch-created for update-packagejson2 should not be created. "
-          if [[ "${{ needs.update-packagejson2.outputs.is-branch-created }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          echo -n "FACT: is-branch-created for update-packagejson3 should not be created. "
-          if [[ "${{ needs.update-packagejson3.outputs.is-branch-created }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-
           echo -n "FACT: branch-name for update-packagejson should be expected. "
           if [[ "${{ needs.update-packagejson.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          echo -n "FACT: branch-name for update-packagejson2 should be exists. "
-          if [[ "${{ needs.update-packagejson2.outputs.branch-name }}" == "test-release/${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
-          echo -n "FACT: branch-name for update-packagejson3 should be exists. "
-          if [[ "${{ needs.update-packagejson3.outputs.branch-name }}" == "test-release/v${{ needs.set-tag.outputs.tag }}" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          echo -n "FACT: branch-name for update-packagejson2 should be empty. "
+          if [[ "${{ needs.update-packagejson2.outputs.branch-name }}" == "" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          echo -n "FACT: branch-name for update-packagejson3 should be empty. "
+          if [[ "${{ needs.update-packagejson3.outputs.branch-name }}" == "" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
   cleanup:
-    if: ${{ needs.update-packagejson3.outputs.is-branch-created == 'true' }}
-    needs: [update-packagejson3]
+    if: ${{ needs.update-packagejson.outputs.is-branch-created == 'true' }}
+    needs: [update-packagejson]
     uses: ./.github/workflows/clean-packagejson-branch.yaml
     with:
-      branch: ${{ needs.update-packagejson3.outputs.branch-name }}
+      branch: ${{ needs.update-packagejson.outputs.branch-name }}
 
   actions-timeline:
     needs: [set-tag, update-packagejson, update-packagejson2, test]
