chore: allow non-release environment

diff --git a/.github/workflows/test-validate-tag.yaml b/.github/workflows/test-validate-tag.yaml
--- a/.github/workflows/test-validate-tag.yaml
+++ b/.github/workflows/test-validate-tag.yaml
@@ -18,7 +18,7 @@ jobs:
     uses: ./.github/workflows/validate-tag.yaml
     with:
       tag: "1.10.0"
-      fail-on-error: true
+      fail-on-invalid: true
     secrets: inherit
 
   validate2:
@@ -26,7 +26,7 @@ jobs:
     uses: ./.github/workflows/validate-tag.yaml
     with:
       tag: "1.0.0"
-      fail-on-error: false
+      fail-on-invalid: false
     secrets: inherit
 
   test:
@@ -36,11 +36,11 @@ jobs:
     steps:
       - name: Test
         run: |
-          echo "DEBUG: validate: ${{ needs.validate.outputs.success }} (${{ needs.validate.outputs.tag }})"
-          echo "DEBUG: validate2: ${{ needs.validate2.outputs.success }} (${{ needs.validate2.outputs.tag }})"
+          echo "DEBUG: validate: ${{ needs.validate.outputs.validated }} (${{ needs.validate.outputs.tag }})"
+          echo "DEBUG: validate2: ${{ needs.validate2.outputs.validated }} (${{ needs.validate2.outputs.tag }})"
 
           echo -n "FACT: tag is newer then current release. "
-          if [[ "${{ needs.validate.outputs.success }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.validate.outputs.validated }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: tag is old then current release. "
-          if [[ "${{ needs.validate2.outputs.success }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ needs.validate2.outputs.validated }}" == "false" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
