chore: typo

diff --git a/.github/workflows/test-check-metas.yaml b/.github/workflows/test-check-metas.yaml
--- a/.github/workflows/test-check-metas.yaml
+++ b/.github/workflows/test-check-metas.yaml
@@ -43,9 +43,10 @@ jobs:
         if: always()
         run: |
           echo "DEBUG: check-metas3: ${{ steps.check-metas3.outputs.meta-exists }}"
+          echo "DEBUG: outcome: ${{ steps.check-metas3.outcome }}"
 
           echo -n "FACT: check-metas3 .meta exists. "
           if [[ "${{ steps.check-metas3.outputs.meta-exists }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
           echo -n "FACT: check-metas3 successfully failed (exit 1) on .meta found. "
-          if [[ "${{ steps.check-metas3.outcome }}" == "failure" ]]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          if [[ "${{ steps.check-metas3.outcome }}" == "failure" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
