chore: additional test

diff --git a/.github/workflows/test-clean-packagejson-branch.yaml b/.github/workflows/test-clean-packagejson-branch.yaml
--- a/.github/workflows/test-clean-packagejson-branch.yaml
+++ b/.github/workflows/test-clean-packagejson-branch.yaml
@@ -35,8 +35,14 @@ jobs:
     with:
       branch: ${{ needs.create-branch.outputs.branch-name }}
 
+  cleanup2:
+    needs: [create-branch]
+    uses: ./.github/workflows/clean-packagejson-branch.yaml
+    with:
+      branch: ${{ needs.create-branch.outputs.branch-name }}
+
   test:
-    needs: [create-branch, cleanup]
+    needs: [create-branch, cleanup, cleanup2]
     runs-on: ubuntu-latest
     steps:
       - name: Test branch deleted
@@ -46,6 +52,11 @@ jobs:
           echo ""
 
           # test
+          echo -n "FACT: cleanup deleted branch. "
+          [[ "${{ needs.cleanup.outputs.branch-deleted }}" == "true" ]] echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+          echo -n "FACT: cleanup2 skip delete branch. "
+          [[ "${{ needs.cleanup2.outputs.branch-deleted }}" != "true" ]] echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
+
           echo -n "FACT: remote branch should not exists. "
           if ! gh api /repos/${{ github.repository }}/branches | jq -r '.[].name' | grep "${{ needs.create-branch.outputs.branch-name }}" >/dev/null; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
 
